# files
DATA_DIRECTORY = 'data/'
MODELS_DIRECTORY = "models/"

# preprocessing
PICTURE_SIZE = (150, 150)
TRAIN_BATCH_SIZE = 32
VALIDATION_BATCH_SIZE = 32
ROTATION_RANGE = 30
WIDTH_SHIFT_RANGE = 0.1
HEIGHT_SHIFT_RANGE = 0.1
SHEAR_RANGE = 0.1
ZOOM_RANGE = 0.1
HORIZONTAL_FLIP = True
VERTICAL_FLIP = False
FILL_MODE = 'nearest'

# model construction
KERNEL_SIZE = (3, 3)
POOL_SIZE = (2, 2)
ACTIVATION = 'relu'
OPTIMIZER_LEARNING_RATE = 1e-4
DROPOUT_RATE = 0

# model launching
EPOCHS = 10

# learning visualization
TRAIN_LINE_STYLE = 'b-'
VALIDATION_LINE_STYLE = 'g-'
